package netcrafts.detective.query;

import net.minecraft.world.entity.MobCategory;

import netcrafts.detective.query.MobCapInfo.CategoryInfo;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Tests for {@link MobCapInfo.CategoryInfo}.
 *
 * CategoryInfo is a plain Java record whose only non-trivial behaviour is
 * {@link CategoryInfo#hasCap()}, which returns {@code true} iff {@code max > 0}.
 * MobCategory enum values are used directly because they are safe to reference
 * without a full Minecraft bootstrap.
 */
class MobCapInfoTest {

    // ------------------------------------------------------------------
    // hasCap()
    // ------------------------------------------------------------------

    @Test
    void hasCap_returnsTrueWhenMaxIsPositive() {
        CategoryInfo info = new CategoryInfo(MobCategory.MONSTER, 5, 70);
        assertTrue(info.hasCap());
    }

    @Test
    void hasCap_returnsTrueWhenCurrentIsZeroButMaxIsPositive() {
        CategoryInfo info = new CategoryInfo(MobCategory.CREATURE, 0, 10);
        assertTrue(info.hasCap());
    }

    @Test
    void hasCap_returnsTrueWhenMaxIsOne() {
        CategoryInfo info = new CategoryInfo(MobCategory.AMBIENT, 0, 1);
        assertTrue(info.hasCap());
    }

    @Test
    void hasCap_returnsFalseWhenMaxIsZero() {
        CategoryInfo info = new CategoryInfo(MobCategory.MISC, 0, 0);
        assertFalse(info.hasCap());
    }

    @Test
    void hasCap_returnsFalseWhenMaxIsNegative() {
        // MISC historically uses -1 to signal "no cap"; verify the guard covers negatives
        CategoryInfo info = new CategoryInfo(MobCategory.MISC, 0, -1);
        assertFalse(info.hasCap());
    }

    @Test
    void hasCap_returnsFalseWhenMaxIsMinusOne() {
        CategoryInfo info = new CategoryInfo(MobCategory.MISC, 3, -1);
        assertFalse(info.hasCap());
    }

    // ------------------------------------------------------------------
    // Record accessors
    // ------------------------------------------------------------------

    @Test
    void category_returnsConstructorValue() {
        CategoryInfo info = new CategoryInfo(MobCategory.CREATURE, 3, 10);
        assertEquals(MobCategory.CREATURE, info.category());
    }

    @Test
    void current_returnsConstructorValue() {
        CategoryInfo info = new CategoryInfo(MobCategory.MONSTER, 7, 70);
        assertEquals(7, info.current());
    }

    @Test
    void max_returnsConstructorValue() {
        CategoryInfo info = new CategoryInfo(MobCategory.MONSTER, 7, 70);
        assertEquals(70, info.max());
    }

    // ------------------------------------------------------------------
    // Record equality and hash code (generated by the compiler)
    // ------------------------------------------------------------------

    @Test
    void equalRecordsAreEqual() {
        CategoryInfo a = new CategoryInfo(MobCategory.MONSTER, 5, 70);
        CategoryInfo b = new CategoryInfo(MobCategory.MONSTER, 5, 70);
        assertEquals(a, b);
    }

    @Test
    void equalRecordsHaveSameHashCode() {
        CategoryInfo a = new CategoryInfo(MobCategory.MONSTER, 5, 70);
        CategoryInfo b = new CategoryInfo(MobCategory.MONSTER, 5, 70);
        assertEquals(a.hashCode(), b.hashCode());
    }

    @Test
    void recordsWithDifferentCurrentAreNotEqual() {
        CategoryInfo a = new CategoryInfo(MobCategory.MONSTER, 5, 70);
        CategoryInfo b = new CategoryInfo(MobCategory.MONSTER, 6, 70);
        assertNotEquals(a, b);
    }

    @Test
    void recordsWithDifferentMaxAreNotEqual() {
        CategoryInfo a = new CategoryInfo(MobCategory.MONSTER, 5, 70);
        CategoryInfo b = new CategoryInfo(MobCategory.MONSTER, 5, 71);
        assertNotEquals(a, b);
    }

    @Test
    void recordsWithDifferentCategoryAreNotEqual() {
        CategoryInfo a = new CategoryInfo(MobCategory.MONSTER, 5, 70);
        CategoryInfo b = new CategoryInfo(MobCategory.CREATURE, 5, 70);
        assertNotEquals(a, b);
    }

    // ------------------------------------------------------------------
    // Boundary / saturation edge cases
    // ------------------------------------------------------------------

    @Test
    void hasCap_whenCurrentEqualsMax_capStillHeld() {
        // Full cap doesn't affect hasCap(); it just checks max > 0
        CategoryInfo info = new CategoryInfo(MobCategory.MONSTER, 70, 70);
        assertTrue(info.hasCap());
    }

    @Test
    void hasCap_whenCurrentExceedsMax_capStillHeld() {
        // Over-cap state (can happen transiently); hasCap only inspects max
        CategoryInfo info = new CategoryInfo(MobCategory.MONSTER, 80, 70);
        assertTrue(info.hasCap());
    }
}
